
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Apr  6 2026 00:34:02 IST (Apr  5 2026 19:04:02 UTC)

// Verification Directory fv/csa_kogge_16bit 

module csa_kogge_16bit(a, b, c, final_sum);
  input [15:0] a, b, c;
  output [17:0] final_sum;
  wire [15:0] a, b, c;
  wire [17:0] final_sum;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_35, n_36, n_37, n_39, n_40, n_41, n_43;
  wire n_44, n_45, n_47, n_48, n_49, n_51, n_52, n_53;
  wire n_55, n_56, n_57, n_59, n_60, n_61, n_63, n_64;
  wire n_65, n_67, n_68, n_69, n_71, n_72, n_73, n_75;
  wire n_76, n_77, n_79, n_80, n_81, n_83, n_84, n_85;
  wire n_87, n_88, n_90;
  ADDHXL g2478__2398(.A (n_1), .B (n_90), .CO (final_sum[17]), .S
       (final_sum[16]));
  OAI21X1 g2479__5107(.A0 (n_88), .A1 (n_87), .B0 (n_4), .Y (n_90));
  MXI2XL g2480__6260(.A (n_35), .B (n_88), .S0 (n_87), .Y
       (final_sum[15]));
  AOI22X1 g2481__4319(.A0 (n_84), .A1 (n_85), .B0 (n_26), .B1 (n_25),
       .Y (n_87));
  MXI2XL g2482__8428(.A (n_83), .B (n_85), .S0 (n_84), .Y
       (final_sum[14]));
  CLKINVX1 g2483(.A (n_83), .Y (n_85));
  AOI22X1 g2484__5526(.A0 (n_80), .A1 (n_81), .B0 (n_10), .B1 (n_9), .Y
       (n_83));
  MXI2XL g2485__6783(.A (n_79), .B (n_81), .S0 (n_80), .Y
       (final_sum[13]));
  CLKINVX1 g2486(.A (n_79), .Y (n_81));
  AOI22X1 g2487__3680(.A0 (n_76), .A1 (n_77), .B0 (n_29), .B1 (n_28),
       .Y (n_79));
  MXI2XL g2488__1617(.A (n_75), .B (n_77), .S0 (n_76), .Y
       (final_sum[12]));
  CLKINVX1 g2489(.A (n_75), .Y (n_77));
  AOI22X1 g2490__2802(.A0 (n_72), .A1 (n_73), .B0 (n_18), .B1 (n_17),
       .Y (n_75));
  MXI2XL g2491__1705(.A (n_71), .B (n_73), .S0 (n_72), .Y
       (final_sum[11]));
  CLKINVX1 g2492(.A (n_71), .Y (n_73));
  AOI22X1 g2493__5122(.A0 (n_68), .A1 (n_69), .B0 (n_12), .B1 (n_11),
       .Y (n_71));
  MXI2XL g2494__8246(.A (n_67), .B (n_69), .S0 (n_68), .Y
       (final_sum[10]));
  CLKINVX1 g2495(.A (n_67), .Y (n_69));
  AOI22X1 g2496__7098(.A0 (n_64), .A1 (n_65), .B0 (n_22), .B1 (n_21),
       .Y (n_67));
  MXI2XL g2497__6131(.A (n_63), .B (n_65), .S0 (n_64), .Y
       (final_sum[9]));
  CLKINVX1 g2498(.A (n_63), .Y (n_65));
  AOI22X1 g2499__1881(.A0 (n_60), .A1 (n_61), .B0 (n_31), .B1 (n_30),
       .Y (n_63));
  MXI2XL g2500__5115(.A (n_59), .B (n_61), .S0 (n_60), .Y
       (final_sum[8]));
  CLKINVX1 g2501(.A (n_59), .Y (n_61));
  MXI2XL g2503__7482(.A (n_55), .B (n_56), .S0 (n_57), .Y
       (final_sum[7]));
  AOI22X1 g2502__4733(.A0 (n_57), .A1 (n_56), .B0 (n_24), .B1 (n_23),
       .Y (n_59));
  CLKINVX1 g2504(.A (n_55), .Y (n_56));
  MXI2XL g2506__6161(.A (n_51), .B (n_52), .S0 (n_53), .Y
       (final_sum[6]));
  AOI22X1 g2505__9315(.A0 (n_53), .A1 (n_52), .B0 (n_20), .B1 (n_19),
       .Y (n_55));
  CLKINVX1 g2507(.A (n_51), .Y (n_52));
  MXI2XL g2509__9945(.A (n_47), .B (n_48), .S0 (n_49), .Y
       (final_sum[5]));
  AOI22X1 g2508__2883(.A0 (n_49), .A1 (n_48), .B0 (n_16), .B1 (n_15),
       .Y (n_51));
  CLKINVX1 g2510(.A (n_47), .Y (n_48));
  MXI2XL g2512__2346(.A (n_43), .B (n_44), .S0 (n_45), .Y
       (final_sum[4]));
  AOI22X1 g2511__1666(.A0 (n_45), .A1 (n_44), .B0 (n_14), .B1 (n_13),
       .Y (n_47));
  CLKINVX1 g2513(.A (n_43), .Y (n_44));
  MXI2XL g2515__7410(.A (n_39), .B (n_40), .S0 (n_41), .Y
       (final_sum[3]));
  AOI22X1 g2514__6417(.A0 (n_41), .A1 (n_40), .B0 (n_8), .B1 (n_7), .Y
       (n_43));
  CLKINVX1 g2516(.A (n_39), .Y (n_40));
  MXI2XL g2518__5477(.A (n_27), .B (n_37), .S0 (n_36), .Y
       (final_sum[2]));
  AOI22X1 g2517__2398(.A0 (n_37), .A1 (n_36), .B0 (n_33), .B1 (n_32),
       .Y (n_39));
  CLKINVX1 g2520(.A (n_35), .Y (n_88));
  XOR2XL g2521__5107(.A (n_5), .B (n_6), .Y (final_sum[1]));
  CLKXOR2X1 g2522__6260(.A (n_33), .B (n_32), .Y (n_36));
  CLKXOR2X1 g2523__4319(.A (n_31), .B (n_30), .Y (n_60));
  CLKXOR2X1 g2524__8428(.A (n_29), .B (n_28), .Y (n_76));
  CLKINVX1 g2519(.A (n_27), .Y (n_37));
  CLKXOR2X1 g2525__5526(.A (n_26), .B (n_25), .Y (n_84));
  CLKXOR2X1 g2526__6783(.A (n_24), .B (n_23), .Y (n_57));
  CLKXOR2X1 g2527__3680(.A (n_22), .B (n_21), .Y (n_64));
  CLKXOR2X1 g2532__1617(.A (n_3), .B (n_2), .Y (n_35));
  CLKXOR2X1 g2529__2802(.A (n_20), .B (n_19), .Y (n_53));
  CLKXOR2X1 g2530__1705(.A (n_18), .B (n_17), .Y (n_72));
  CLKXOR2X1 g2531__5122(.A (n_16), .B (n_15), .Y (n_49));
  CLKXOR2X1 g2528__8246(.A (n_14), .B (n_13), .Y (n_45));
  CLKXOR2X1 g2533__7098(.A (n_12), .B (n_11), .Y (n_68));
  CLKXOR2X1 g2534__6131(.A (n_10), .B (n_9), .Y (n_80));
  CLKXOR2X1 g2535__1881(.A (n_8), .B (n_7), .Y (n_41));
  NAND2XL g2536__5115(.A (n_6), .B (n_5), .Y (n_27));
  NAND2XL g2537__7482(.A (n_3), .B (n_2), .Y (n_4));
  ADDFXL g2545__4733(.A (a[11]), .B (b[11]), .CI (c[11]), .CO (n_29),
       .S (n_17));
  ADDFXL g2553__6161(.A (a[1]), .B (b[1]), .CI (c[1]), .CO (n_33), .S
       (n_5));
  ADDFXL g2552__9315(.A (a[2]), .B (b[2]), .CI (c[2]), .CO (n_8), .S
       (n_32));
  ADDFXL g2551__9945(.A (a[9]), .B (b[9]), .CI (c[9]), .CO (n_12), .S
       (n_21));
  ADDFXL g2550__2883(.A (a[13]), .B (b[13]), .CI (c[13]), .CO (n_26),
       .S (n_9));
  ADDFXL g2549__2346(.A (a[10]), .B (b[10]), .CI (c[10]), .CO (n_18),
       .S (n_11));
  ADDFXL g2548__1666(.A (a[4]), .B (b[4]), .CI (c[4]), .CO (n_16), .S
       (n_13));
  ADDFXL g2547__7410(.A (a[15]), .B (b[15]), .CI (c[15]), .CO (n_1), .S
       (n_2));
  ADDFXL g2546__6417(.A (a[6]), .B (b[6]), .CI (c[6]), .CO (n_24), .S
       (n_19));
  ADDFXL g2541__5477(.A (a[14]), .B (b[14]), .CI (c[14]), .CO (n_3), .S
       (n_25));
  ADDFXL g2544__2398(.A (a[3]), .B (b[3]), .CI (c[3]), .CO (n_14), .S
       (n_7));
  ADDFXL g2543__5107(.A (a[5]), .B (b[5]), .CI (c[5]), .CO (n_20), .S
       (n_15));
  ADDFXL g2542__6260(.A (a[12]), .B (b[12]), .CI (c[12]), .CO (n_10),
       .S (n_28));
  ADDFXL g2539__4319(.A (a[8]), .B (b[8]), .CI (c[8]), .CO (n_22), .S
       (n_30));
  ADDFX1 g2540__8428(.A (b[0]), .B (a[0]), .CI (c[0]), .CO (n_6), .S
       (final_sum[0]));
  ADDFXL g2538__5526(.A (a[7]), .B (b[7]), .CI (c[7]), .CO (n_31), .S
       (n_23));
endmodule

